workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: Betix Sports&Trainings

    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files \
            com.betix.sportstrainings \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles
          echo "=== PROFILES ==="
          ls ~/Library/MobileDevice/Provisioning\ Profiles/
          security find-identity -v -p codesigning

      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect create-certificate \
            --type IOS_DISTRIBUTION \
            --save-locally
          app-store-connect fetch-signing-files \
            com.betix.sportstrainings \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath build/Betix.xcarchive \
            -exportPath build/ \
            -exportOptionsPlist exportOptions.plist

    artifacts:
      - build/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
