workflows:
  ios-release:
    name: iOS Release
    environment:
      ios_signing:
        distribution_type: app_store  # или ad_hoc
        bundle_identifier: com.betix.sportstrainings
    scripts:
      - name: Build iOS
        script: |
          xcodebuild \
            -project App.xcodeproj \
            -scheme LineWorkoutFlow \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath build/LineWorkoutFlow.xcarchive \
            archive
